# Generated by Django 4.1 on 2022-09-02 17:51

from django.db import migrations, models
import django_cpf_cnpj.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("cnpj", django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ("email", models.EmailField(max_length=50)),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("endereco1", models.CharField(blank=True, max_length=50, null=True)),
                ("endereco2", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
