# Generated by Django 4.1 on 2022-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_cnpj_alter_empresa_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="telefone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
