# Generated by Django 4.1 on 2022-09-02 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", django_cpf_cnpj.fields.CPFField(max_length=14)),
                ("cnpj", django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ("email", models.EmailField(max_length=50)),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("endereco1", models.CharField(blank=True, max_length=50, null=True)),
                ("endereco2", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
