# Generated by Django 4.1 on 2022-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0002_remove_colaborador_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="telefone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
