# Generated by Django 4.1 on 2022-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0003_alter_colaborador_email_alter_colaborador_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
