# Generated by Django 4.1 on 2022-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0005_alter_colaborador_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="primeiro_nome",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="colaborador",
            name="ultimo_nome",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
