# Generated by Django 4.1 on 2022-09-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0006_colaborador_primeiro_nome_colaborador_ultimo_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="endereco1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Linha 1"
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="endereco2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Linha 2"
            ),
        ),
    ]
